{% set name = "paicos" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/paicos-{{ version }}.tar.gz
  sha256: 44132561923b8f554f0b8a75cfdbf63778a19a332503a7e65fa8a905ba975660

build:
  skip: True  # [py<38]
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
    - numpy                                 # [build_platform != target_platform]
  host:
    - python
    - cython >=0.29.21
    - numpy
    - setuptools
    - wheel
    - pip
  run:
    - python
    - scipy
    - {{ pin_compatible("numpy") }}
    - h5py
    - astropy
    - numba
    - matplotlib-base

test:
  imports:
    - paicos
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tberlok/paicos
  summary: An object-oriented Python package for analysis of (cosmological) simulations performed with Arepo.
  license: GPL-2.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tberlok
