{% set name = "paicos" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/paicos-{{ version }}.tar.gz
  sha256: 1cee7200908abdb04c885d94a3e49a8dd2bf25add0a8d51be22edd513e3dc9a0

build:
  skip: true  # [py<38]
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
    - numpy                                 # [build_platform != target_platform]
  host:
    - python
    - cython >=0.29.21
    - numpy
    - setuptools
    - wheel
    - pip
  run:
    - python
    - scipy
    - h5py
    - astropy
    - numba
    - matplotlib-base

test:
  imports:
    - paicos
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tberlok/paicos
  summary: An object-oriented Python package for analysis of (cosmological) simulations performed with Arepo.
  license: GPL-2.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tberlok
